### ISSUE TITLE
Does this require AndroidX?

### ISSUE THREAD

**Issue by codeversed** [Ramotion/fluid-slider-android#38]
I am having issues getting this to work with our project and it seems that you need to use AndroidX for this library to compile nicely? 

*Error*
```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:41:5-212:19 to override.
```

Would it be possible to do a backport or is there a reason that you are using AndroidX? I did not see a seperate branch for Support/Material, maybe I missed it.

**Comment by golovin47** [comment]
Hello, @codeversed. Yes, this lib require androidx. It is necessary to migrate android project to androidx because there won't be any sdk updates from google for support libraries after sdk28 https://android-developers.googleblog.com/2018/05/hello-world-androidx.html. If you still don't want to migrate your project to androidx, you may use previous versions of this lib like 0.3.0.
